### ISSUE TITLE
Stuttering audio on RPi 4

### ISSUE THREAD

**Issue by CaelThunderwing** [PromyLOPh/pianobar#688] opened 2019-08-29 02:16 UTC
### Audio Stutters on RPi4 on Default Samplerate
after manually compiling Pianobar audio playback is stuttering as-if the system cannot handle it. If you open Chromium and load Pandora directly. plays back just fine. 

### Your environment
* version of pianobar: Latest git commit
* your Linux distribution and release version: Raspbian Buster
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself) (default "make all" from when i last compiled)
* your config file
User *Redacted*
Password *Redacted*
audio_quality= high

### Steps to reproduce
loaded after finishing compiling ad making config file.

### Expected behaviour
Smooth as buttery silk audio playback

### Actual behaviour
audio stutters  as if the Raspberry Pi 4 cannot keep up every second  (as if its buffering audio every second)

EDIT @10:57PM EST:
going thru the sample config in the source, finding about the sample_rate option.. the stutter goes away setting to 48kHz (48,000)

**Comment by PromyLOPh** [comment] 2019-08-29 08:53
Hm, weird. What audio output are you using? ALSA, pulseaudio? You can try setting ``default_driver=pulse`` in your ~/.libao if you’ve got pulseaudio installed. Afaik libao defaults to ALSA.

**Comment by CaelThunderwing** [comment] 2019-08-29 15:45
ALSA (and to HDMI not the analouge out)

‪On Thu, Aug 29, 2019 at 4:53 AM ‫لارس · Lars‬‎ <notifications@github.com>
wrote:‬

**Comment by PromyLOPh** [comment] 2019-08-30 07:38
Best guess right now: Resampling inside pianobar happens before its audio buffer and thus is immune to latency spikes (up to 5 seconds by default). Whatever resampling is happening after pianobar hands off data to libao (which does not resample) should be using larger buffers to compensate for that.

**Comment by lewisdonofrio** [comment] 2019-09-29 14:23
I get the same thing, please advise.

**Comment by lewisdonofrio** [comment] 2019-09-29 15:31
kael how's you do that I only get " Unrecognized key sampling_rate at /home/pi/.config/pianobar/config:23" when I try sampling_rate=48000 ;(

**Comment by PromyLOPh** [comment] 2019-09-29 16:38
sampling_rate != sample_rate

**Comment by lewisdonofrio** [comment] 2019-09-29 16:38
facepalm trying now

**Comment by lewisdonofrio** [comment] 2019-09-29 16:40
tried and still brokenup way slow
"Unrecognized key sample_rate at /home/pi/.config/pianobar/config:24"
used "sample_rate=48000" ;(

**Comment by PromyLOPh** [comment] 2019-09-29 17:45
Which version are you using? There’s no release with this feature yet, so you have to compile the master branch yourself.

**Comment by lewisdonofrio** [comment] 2019-09-29 17:48
standard version in raspbian 2019.02.14

**Comment by lewisdonofrio** [comment] 2019-09-29 17:55
when I try to compile I get:
pi@raspberrypi:~ $ sudo apt-get remove pianobar
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libao-common libao4 libpiano0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  pianobar
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 108 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 179859 files and directories currently installed.)
Removing pianobar (2019.02.14-1) ...
Processing triggers for man-db (2.8.5-2) ...
pi@raspberrypi:~ $ git clone https://github.com/PromyLOPh/pianobar.git
Cloning into 'pianobar'...
remote: Enumerating objects: 4849, done.
remote: Total 4849 (delta 0), reused 0 (delta 0), pack-reused 4849
Receiving objects: 100% (4849/4849), 1.27 MiB | 6.85 MiB/s, done.
Resolving deltas: 100% (3585/3585), done.
pi@raspberrypi:~ $ sudo apt-get install curl-devel coreutils gcc-c++ json-c-devel libgcrypt-devel libao-devel gnutls-devel ffmpeg-devel libmad-devel faad2-devel -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package curl-devel
E: Unable to locate package gcc-c+
E: Couldn't find any package by regex 'gcc-c+'
E: Unable to locate package json-c-devel
E: Unable to locate package libgcrypt-devel
E: Unable to locate package libao-devel
E: Unable to locate package gnutls-devel
E: Unable to locate package ffmpeg-devel
E: Unable to locate package libmad-devel
E: Unable to locate package faad2-devel
pi@raspberrypi:~ $ 


;(

**Comment by lewisdonofrio** [comment] 2019-09-29 18:24
mybad but still sad
pi@raspberrypi:~ $ sudo apt-get install libgcrypt11-dev libjson0-dev libgnutls28-dev libav-tools libao-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

Package libgcrypt11-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgcrypt11-dev' has no installation candidate
E: Unable to locate package libjson0-dev
E: Package 'libav-tools' has no installation candidate

raspbian is debian based not fedora....but still unable to install what is needed to compile?

**Comment by edward-p** [comment] 2019-09-29 18:37
Use `apt search` to search packages.

**Comment by lewisdonofrio** [comment] 2019-09-29 19:00
is this libgcrypt11-dev older version of libgcrypt20-dev ?

**Comment by lewisdonofrio** [comment] 2019-09-29 19:45
Which libjson do I need?
pi@raspberrypi:~ $ apt-cache search  libjson0-dev
pi@raspberrypi:~ $ apt-cache search  libjson
bit-babbler - BitBabbler hardware TRNG and kernel entropy source support
devscripts - scripts to make the life of a Debian Package maintainer easier
libjson-any-perl - wrapper class for the various JSON classes
libjson-c-dev - JSON manipulation library - development files
libjson-c-doc - JSON manipulation library - documentation files
libjson-c3 - JSON manipulation library - shared library
libjson-glib-1.0-0 - GLib JSON manipulation library
libjson-glib-1.0-common - GLib JSON manipulation library (common files)
libjson-glib-dev - GLib JSON manipulation library (development files)
libjson-glib-doc - GLib JSON manipulation library (documentation)
libjson-java - library for transforming Java objects and XML to JSON and back again
libjson-maybexs-perl - interface to the best available JSON module
libjson-multivalueordered-perl - module to handle JSON like {"a":1, "a":2}
libjson-perl - module for manipulating JSON-formatted data
libjson-pointer-perl - Perl implementation of JSON Pointer (RFC6901)
libjson-pp-perl - module for manipulating JSON-formatted data (Pure Perl)
libjson-rpc-perl - Perl implementation of JSON-RPC 1.1 protocol
libjson-simple-doc - documentation for libjson-simple-java
libjson-simple-java - Simple, lightweight and efficient JSON toolkit for Java
libjson-smart-java - JSON Small and Fast Parser
libjson-spirit-dev - C++ JSON Parser/Generator implemented with Boost Spirit
libjson-static-camlp4-dev - JSON validator and converter for OCaml
libjson-types-perl - variable type utility for JSON encoding
libjson-validator-perl - module to validate data against a JSON schema
libjson-webtoken-perl - JSON Web Token (JWT) implementation
libjson-wheel-ocaml-dev - OCaml API to JSON data format
libjson-xs-perl - module for manipulating JSON-formatted data (C/XS-accelerated)
libjson4s-java - Single AST to be used by other scala json libraries
libjsonb-api-java - Java API for JSON Binding (JSON-B)
libjsoncpp-dev - library for reading and writing JSON for C++ (devel files)
libjsoncpp-doc - API documentation for libjsoncpp-dev
libjsoncpp1 - library for reading and writing JSON for C++
libjsonm-ocaml - Non-blocking streaming JSON codec for OCaml (plugins)
libjsonm-ocaml-dev - Non-blocking streaming JSON codec for OCaml
libjsonm-ocaml-doc - Non-blocking streaming JSON codec for OCaml (documentation)
libjsonp-java - Java API for JSON Processing
libjsonp-java-doc - Java API for JSON Processing (documentation)
libjsonparser-dev - Very low footprint JSON parser written in portable ANSI C - development headers
libjsonparser1.1 - Very low footprint JSON parser written in portable ANSI C
libjsonpath-java - Jayway JsonPath - XPath like expressions for JSON
libjsonrpc-glib-1.0-1 - JSON-RPC library for GLib
libjsonrpc-glib-1.0-dev - JSON-RPC library for GLib - development files
libjsonrpc-glib-doc - JSON-RPC library for GLib - documentation
libjsonrpccpp-client0 - library implementing json-rpc C++ clients
libjsonrpccpp-client0-dbg - debugging symbols for libjsonrpccpp-client0
libjsonrpccpp-common0 - common functionality for server and client library
libjsonrpccpp-common0-dbg - debugging symbols for libjsonrpccpp-common0
libjsonrpccpp-dev - development files for JSON-RPC C++ framework
libjsonrpccpp-server0 - library implementing json-rpc C++ servers
libjsonrpccpp-server0-dbg - debugging symbols for libjsonrpccpp-server0
libjsonrpccpp-stub0 - library for stub generation of libjsonrpccpp based applications
libjsonrpccpp-stub0-dbg - debugging symbols for libjsonrpccpp-stub0
libjsonrpccpp-tools - stub generator for libjsonrpccpp based applications
libmoosex-types-json-perl - module providing JSON-constrained strings
libyojson-ocaml - JSON library for OCaml - runtime package
libyojson-ocaml-dev - JSON library for OCaml - development package
perl - Larry Wall's Practical Extraction and Report Language

**Comment by lewisdonofrio** [comment] 2019-09-30 00:06
k got that but missing:

pi@raspberrypi:~ $ sudo apt-get install libgcrypt20-dev libjson-c-dev libgnutls28-dev libav-tools libao-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Package 'libav-tools' has no installation candidate
pi@raspberrypi:~ $

**Comment by lewisdonofrio** [comment] 2019-10-01 19:23
Still trying to get this to compile, anyone have a newer wiki for rpi3/4's?  

***SNIPPED**
pi@raspberrypi:~/pianobar $ make
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
    CC  src/main.c
In file included from src/main.c:24:
src/config.h:14:10: fatal error: libavfilter/version.h: No such file or directory
 #include <libavfilter/version.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:108: src/main.o] Error 1
pi@raspberrypi:~/pianobar $ 
**SNIPPED** 

;(

**Comment by PromyLOPh** [comment] 2019-10-02 12:02
Sorry, but this is a bug tracker, not a support forum.

**Comment by lewisdonofrio** [comment] 2019-10-02 17:16
ok, I'm just trying to compile this goodness..... do I "have" to compile ffmpeg or use OS package if I'm compiling pianobar?

**Comment by PromyLOPh** [comment] 2019-10-02 17:30
Either should be fine, but for the latter you usually need to install
development files. This depends on the distro though.

**Comment by lewisdonofrio** [comment] 2019-10-02 17:51
ok just consider this issue is for rpi's running raspbian that is why we are here....and how to get it to not stutter (or as I call it playing each note so long.....)

**Comment by lewisdonofrio** [comment] 2019-10-02 17:52
are you folks on irc.freenode.net?

**Comment by lewisdonofrio** [comment] 2019-10-07 02:26
needed libcurl4-gnutls-dev and it sounded great for 30 seconds of playback but now sounds slow again, I'm so confused.....

**Comment by lewisdonofrio** [comment] 2019-10-08 00:30
Now its working after i change a station - well see how long it holds out....thank you to all you good folks do...

**Comment by lewisdonofrio** [comment] 2019-10-08 01:17
It's playing fine now, still getting these "ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front" but it's at least playing now, have not rebooted just working and enjoying currently.

**Comment by lewisdonofrio** [comment] 2019-10-08 01:29
ugh doing it again.....bah

**Comment by lewisdonofrio** [comment] 2019-10-08 21:58
and now it's working, do I need to break out gdb ;(

**Comment by lewisdonofrio** [comment] 2019-10-08 22:00
very next song stuttering very bad ;(  How can I help?

**Comment by lewisdonofrio** [comment] 2019-10-08 22:08
so one out of four songs plays fine.....

**Comment by lewisdonofrio** [comment] 2019-10-08 22:47
been fine last 12 songs.....just waiting for it to go back to bad sounding....

**Comment by lewisdonofrio** [comment] 2019-10-09 01:50
after last four hours nothing changes and next song was messed up I exited, I hope my feedback is good and not unwanted.....

**Comment by lewisdonofrio** [comment] 2019-10-09 01:53
so if I run and exit gracefully (q)uit like 20 times it does start working again....

**Comment by lewisdonofrio** [comment] 2019-10-09 02:05
ok last post about this am I suppose to be at this version when pulling from git? 2019.02.14-dev?

**Comment by PromyLOPh** [comment] 2019-10-09 06:38
Alright, I see you’re frustrated it is not working properly, but this is enough. Right now it does not look like an issue caused by pianobar, so I can’t do anything to fix it. And, as I said before, this is not a generic support forum.

(Yes, 2019.02.14-dev is the current git version.)

**Closed** 2019-12-18 10:50 UTC
Labels: invalid
